INSERT INTO `db_springboot_backend`.`regiones` (`id`, `nombre`) VALUES (1, 'Sudamérica');
INSERT INTO `db_springboot_backend`.`regiones` (`id`, `nombre`) VALUES (2, 'Centroamérica');
INSERT INTO `db_springboot_backend`.`regiones` (`id`, `nombre`) VALUES (3, 'Norteamérica');
INSERT INTO `db_springboot_backend`.`regiones` (`id`, `nombre`) VALUES (4, 'Europa');
INSERT INTO `db_springboot_backend`.`regiones` (`id`, `nombre`) VALUES (5, 'Asia');
INSERT INTO `db_springboot_backend`.`regiones` (`id`, `nombre`) VALUES (6, 'Africa');
INSERT INTO `db_springboot_backend`.`regiones` (`id`, `nombre`) VALUES (7, 'OceanÃ­a');
INSERT INTO `db_springboot_backend`.`regiones` (`id`, `nombre`) VALUES (8, 'Antártida');

INSERT INTO `db_springboot_backend`.`clientes` (`region_id`, `nombre`, `apellido`, `email`, `create_at`) VALUES (1, 'Edgard', 'Marquez', 'prueba1@empresa.com', '2020-01-01');
INSERT INTO `db_springboot_backend`.`clientes` (`region_id`, `nombre`, `apellido`, `email`, `create_at`) VALUES (1, 'Leon', 'Mendoza', 'prueba2@empresa.com', '2020-01-02');
INSERT INTO `db_springboot_backend`.`clientes` (`region_id`, `nombre`, `apellido`, `email`, `create_at`) VALUES (1, 'Martin', 'Lavalle', 'prueba3@empresa.com', '2020-01-03');
INSERT INTO `db_springboot_backend`.`clientes` (`region_id`, `nombre`, `apellido`, `email`, `create_at`) VALUES (1, 'Gonzalo', 'Garcia', 'prueba4@empresa.com', '2020-01-04');
INSERT INTO `db_springboot_backend`.`clientes` (`region_id`, `nombre`, `apellido`, `email`, `create_at`) VALUES (1, 'Maria', 'Perez', 'maria.perez@empresa.com', '2020-01-04');
INSERT INTO `db_springboot_backend`.`clientes` (`region_id`, `nombre`, `apellido`, `email`, `create_at`) VALUES (1, 'Ana', 'Lopez', 'ana.lopez@empresa.com', '2020-01-04');
INSERT INTO `db_springboot_backend`.`clientes` (`region_id`, `nombre`, `apellido`, `email`, `create_at`) VALUES (1, 'Javier', 'Cruz', 'javier.cruz@empresa.com', '2020-01-04');
INSERT INTO `db_springboot_backend`.`clientes` (`region_id`, `nombre`, `apellido`, `email`, `create_at`) VALUES (1, 'Manuel', 'Gonzales', 'manuel.gonzales@empresa.com', '2020-01-04');
INSERT INTO `db_springboot_backend`.`clientes` (`region_id`, `nombre`, `apellido`, `email`, `create_at`) VALUES (1, 'Luis', 'Palma', 'luis.palma@empresa.com', '2020-01-04');
INSERT INTO `db_springboot_backend`.`clientes` (`region_id`, `nombre`, `apellido`, `email`, `create_at`) VALUES (1, 'Edgard', 'Marquez', 'prueba1@empresa.com', '2020-01-01');
INSERT INTO `db_springboot_backend`.`clientes` (`region_id`, `nombre`, `apellido`, `email`, `create_at`) VALUES (1, 'Leon', 'Mendoza', 'prueba2@empresa.com', '2020-01-02');
INSERT INTO `db_springboot_backend`.`clientes` (`region_id`, `nombre`, `apellido`, `email`, `create_at`) VALUES (1, 'Martin', 'Lavalle', 'prueba3@empresa.com', '2020-01-03');
INSERT INTO `db_springboot_backend`.`clientes` (`region_id`, `nombre`, `apellido`, `email`, `create_at`) VALUES (1, 'Gonzalo', 'Garcia', 'prueba4@empresa.com', '2020-01-04');
INSERT INTO `db_springboot_backend`.`clientes` (`region_id`, `nombre`, `apellido`, `email`, `create_at`) VALUES (1, 'Maria', 'Perez', 'maria.perez@empresa.com', '2020-01-04');
INSERT INTO `db_springboot_backend`.`clientes` (`region_id`, `nombre`, `apellido`, `email`, `create_at`) VALUES (1, 'Ana', 'Lopez', 'ana.lopez@empresa.com', '2020-01-04');
INSERT INTO `db_springboot_backend`.`clientes` (`region_id`, `nombre`, `apellido`, `email`, `create_at`) VALUES (1, 'Javier', 'Cruz', 'javier.cruz@empresa.com', '2020-01-04');
INSERT INTO `db_springboot_backend`.`clientes` (`region_id`, `nombre`, `apellido`, `email`, `create_at`) VALUES (1, 'Manuel', 'Gonzales', 'manuel.gonzales@empresa.com', '2020-01-04');
INSERT INTO `db_springboot_backend`.`clientes` (`region_id`, `nombre`, `apellido`, `email`, `create_at`) VALUES (1, 'Luis', 'Palma', 'luis.palma@empresa.com', '2020-01-04');
INSERT INTO `db_springboot_backend`.`clientes` (`region_id`, `nombre`, `apellido`, `email`, `create_at`) VALUES (1, 'Edgard', 'Marquez', 'prueba1@empresa.com', '2020-01-01');
INSERT INTO `db_springboot_backend`.`clientes` (`region_id`, `nombre`, `apellido`, `email`, `create_at`) VALUES (1, 'Leon', 'Mendoza', 'prueba2@empresa.com', '2020-01-02');
INSERT INTO `db_springboot_backend`.`clientes` (`region_id`, `nombre`, `apellido`, `email`, `create_at`) VALUES (1, 'Martin', 'Lavalle', 'prueba3@empresa.com', '2020-01-03');
INSERT INTO `db_springboot_backend`.`clientes` (`region_id`, `nombre`, `apellido`, `email`, `create_at`) VALUES (1, 'Gonzalo', 'Garcia', 'prueba4@empresa.com', '2020-01-04');
INSERT INTO `db_springboot_backend`.`clientes` (`region_id`, `nombre`, `apellido`, `email`, `create_at`) VALUES (1, 'Maria', 'Perez', 'maria.perez@empresa.com', '2020-01-04');
INSERT INTO `db_springboot_backend`.`clientes` (`region_id`, `nombre`, `apellido`, `email`, `create_at`) VALUES (1, 'Ana', 'Lopez', 'ana.lopez@empresa.com', '2020-01-04');
INSERT INTO `db_springboot_backend`.`clientes` (`region_id`, `nombre`, `apellido`, `email`, `create_at`) VALUES (1, 'Javier', 'Cruz', 'javier.cruz@empresa.com', '2020-01-04');
INSERT INTO `db_springboot_backend`.`clientes` (`region_id`, `nombre`, `apellido`, `email`, `create_at`) VALUES (1, 'Manuel', 'Gonzales', 'manuel.gonzales@empresa.com', '2020-01-04');
INSERT INTO `db_springboot_backend`.`clientes` (`region_id`, `nombre`, `apellido`, `email`, `create_at`) VALUES (1, 'Luis', 'Palma', 'luis.palma@empresa.com', '2020-01-04');
INSERT INTO `db_springboot_backend`.`clientes` (`region_id`, `nombre`, `apellido`, `email`, `create_at`) VALUES (1, 'Edgard', 'Marquez', 'prueba1@empresa.com', '2020-01-01');
INSERT INTO `db_springboot_backend`.`clientes` (`region_id`, `nombre`, `apellido`, `email`, `create_at`) VALUES (1, 'Leon', 'Mendoza', 'prueba2@empresa.com', '2020-01-02');
INSERT INTO `db_springboot_backend`.`clientes` (`region_id`, `nombre`, `apellido`, `email`, `create_at`) VALUES (1, 'Martin', 'Lavalle', 'prueba3@empresa.com', '2020-01-03');
INSERT INTO `db_springboot_backend`.`clientes` (`region_id`, `nombre`, `apellido`, `email`, `create_at`) VALUES (1, 'Gonzalo', 'Garcia', 'prueba4@empresa.com', '2020-01-04');
INSERT INTO `db_springboot_backend`.`clientes` (`region_id`, `nombre`, `apellido`, `email`, `create_at`) VALUES (1, 'Maria', 'Perez', 'maria.perez@empresa.com', '2020-01-04');
INSERT INTO `db_springboot_backend`.`clientes` (`region_id`, `nombre`, `apellido`, `email`, `create_at`) VALUES (1, 'Ana', 'Lopez', 'ana.lopez@empresa.com', '2020-01-04');
INSERT INTO `db_springboot_backend`.`clientes` (`region_id`, `nombre`, `apellido`, `email`, `create_at`) VALUES (1, 'Javier', 'Cruz', 'javier.cruz@empresa.com', '2020-01-04');
INSERT INTO `db_springboot_backend`.`clientes` (`region_id`, `nombre`, `apellido`, `email`, `create_at`) VALUES (1, 'Manuel', 'Gonzales', 'manuel.gonzales@empresa.com', '2020-01-04');
INSERT INTO `db_springboot_backend`.`clientes` (`region_id`, `nombre`, `apellido`, `email`, `create_at`) VALUES (1, 'Luis', 'Palma', 'luis.palma@empresa.com', '2020-01-04');
INSERT INTO `db_springboot_backend`.`clientes` (`region_id`, `nombre`, `apellido`, `email`, `create_at`) VALUES (1, 'Edgard', 'Marquez', 'prueba1@empresa.com', '2020-01-01');
INSERT INTO `db_springboot_backend`.`clientes` (`region_id`, `nombre`, `apellido`, `email`, `create_at`) VALUES (1, 'Leon', 'Mendoza', 'prueba2@empresa.com', '2020-01-02');
INSERT INTO `db_springboot_backend`.`clientes` (`region_id`, `nombre`, `apellido`, `email`, `create_at`) VALUES (1, 'Martin', 'Lavalle', 'prueba3@empresa.com', '2020-01-03');
INSERT INTO `db_springboot_backend`.`clientes` (`region_id`, `nombre`, `apellido`, `email`, `create_at`) VALUES (1, 'Gonzalo', 'Garcia', 'prueba4@empresa.com', '2020-01-04');
INSERT INTO `db_springboot_backend`.`clientes` (`region_id`, `nombre`, `apellido`, `email`, `create_at`) VALUES (1, 'Maria', 'Perez', 'maria.perez@empresa.com', '2020-01-04');
INSERT INTO `db_springboot_backend`.`clientes` (`region_id`, `nombre`, `apellido`, `email`, `create_at`) VALUES (1, 'Ana', 'Lopez', 'ana.lopez@empresa.com', '2020-01-04');
INSERT INTO `db_springboot_backend`.`clientes` (`region_id`, `nombre`, `apellido`, `email`, `create_at`) VALUES (1, 'Javier', 'Cruz', 'javier.cruz@empresa.com', '2020-01-04');
INSERT INTO `db_springboot_backend`.`clientes` (`region_id`, `nombre`, `apellido`, `email`, `create_at`) VALUES (1, 'Manuel', 'Gonzales', 'manuel.gonzales@empresa.com', '2020-01-04');
INSERT INTO `db_springboot_backend`.`clientes` (`region_id`, `nombre`, `apellido`, `email`, `create_at`) VALUES (1, 'Luis', 'Palma', 'luis.palma@empresa.com', '2020-01-04');
INSERT INTO `db_springboot_backend`.`clientes` (`region_id`, `nombre`, `apellido`, `email`, `create_at`) VALUES (1, 'Edgard', 'Marquez', 'prueba1@empresa.com', '2020-01-01');
INSERT INTO `db_springboot_backend`.`clientes` (`region_id`, `nombre`, `apellido`, `email`, `create_at`) VALUES (1, 'Leon', 'Mendoza', 'prueba2@empresa.com', '2020-01-02');
INSERT INTO `db_springboot_backend`.`clientes` (`region_id`, `nombre`, `apellido`, `email`, `create_at`) VALUES (1, 'Martin', 'Lavalle', 'prueba3@empresa.com', '2020-01-03');
INSERT INTO `db_springboot_backend`.`clientes` (`region_id`, `nombre`, `apellido`, `email`, `create_at`) VALUES (1, 'Gonzalo', 'Garcia', 'prueba4@empresa.com', '2020-01-04');
INSERT INTO `db_springboot_backend`.`clientes` (`region_id`, `nombre`, `apellido`, `email`, `create_at`) VALUES (1, 'Maria', 'Perez', 'maria.perez@empresa.com', '2020-01-04');
INSERT INTO `db_springboot_backend`.`clientes` (`region_id`, `nombre`, `apellido`, `email`, `create_at`) VALUES (1, 'Ana', 'Lopez', 'ana.lopez@empresa.com', '2020-01-04');
INSERT INTO `db_springboot_backend`.`clientes` (`region_id`, `nombre`, `apellido`, `email`, `create_at`) VALUES (1, 'Javier', 'Cruz', 'javier.cruz@empresa.com', '2020-01-04');
INSERT INTO `db_springboot_backend`.`clientes` (`region_id`, `nombre`, `apellido`, `email`, `create_at`) VALUES (1, 'Manuel', 'Gonzales', 'manuel.gonzales@empresa.com', '2020-01-04');
INSERT INTO `db_springboot_backend`.`clientes` (`region_id`, `nombre`, `apellido`, `email`, `create_at`) VALUES (1, 'Luis', 'Palma', 'luis.palma@empresa.com', '2020-01-04');
INSERT INTO `db_springboot_backend`.`clientes` (`region_id`, `nombre`, `apellido`, `email`, `create_at`) VALUES (1, 'Edgard', 'Marquez', 'prueba1@empresa.com', '2020-01-01');
INSERT INTO `db_springboot_backend`.`clientes` (`region_id`, `nombre`, `apellido`, `email`, `create_at`) VALUES (1, 'Leon', 'Mendoza', 'prueba2@empresa.com', '2020-01-02');
INSERT INTO `db_springboot_backend`.`clientes` (`region_id`, `nombre`, `apellido`, `email`, `create_at`) VALUES (1, 'Martin', 'Lavalle', 'prueba3@empresa.com', '2020-01-03');
INSERT INTO `db_springboot_backend`.`clientes` (`region_id`, `nombre`, `apellido`, `email`, `create_at`) VALUES (1, 'Gonzalo', 'Garcia', 'prueba4@empresa.com', '2020-01-04');
INSERT INTO `db_springboot_backend`.`clientes` (`region_id`, `nombre`, `apellido`, `email`, `create_at`) VALUES (1, 'Maria', 'Perez', 'maria.perez@empresa.com', '2020-01-04');
INSERT INTO `db_springboot_backend`.`clientes` (`region_id`, `nombre`, `apellido`, `email`, `create_at`) VALUES (1, 'Ana', 'Lopez', 'ana.lopez@empresa.com', '2020-01-04');
INSERT INTO `db_springboot_backend`.`clientes` (`region_id`, `nombre`, `apellido`, `email`, `create_at`) VALUES (1, 'Javier', 'Cruz', 'javier.cruz@empresa.com', '2020-01-04');
INSERT INTO `db_springboot_backend`.`clientes` (`region_id`, `nombre`, `apellido`, `email`, `create_at`) VALUES (1, 'Manuel', 'Gonzales', 'manuel.gonzales@empresa.com', '2020-01-04');
INSERT INTO `db_springboot_backend`.`clientes` (`region_id`, `nombre`, `apellido`, `email`, `create_at`) VALUES (1, 'Luis', 'Palma', 'luis.palma@empresa.com', '2020-01-04');
INSERT INTO `db_springboot_backend`.`clientes` (`region_id`, `nombre`, `apellido`, `email`, `create_at`) VALUES (1, 'Edgard', 'Marquez', 'prueba1@empresa.com', '2020-01-01');
INSERT INTO `db_springboot_backend`.`clientes` (`region_id`, `nombre`, `apellido`, `email`, `create_at`) VALUES (1, 'Leon', 'Mendoza', 'prueba2@empresa.com', '2020-01-02');
INSERT INTO `db_springboot_backend`.`clientes` (`region_id`, `nombre`, `apellido`, `email`, `create_at`) VALUES (1, 'Martin', 'Lavalle', 'prueba3@empresa.com', '2020-01-03');
INSERT INTO `db_springboot_backend`.`clientes` (`region_id`, `nombre`, `apellido`, `email`, `create_at`) VALUES (1, 'Gonzalo', 'Garcia', 'prueba4@empresa.com', '2020-01-04');
INSERT INTO `db_springboot_backend`.`clientes` (`region_id`, `nombre`, `apellido`, `email`, `create_at`) VALUES (1, 'Maria', 'Perez', 'maria.perez@empresa.com', '2020-01-04');
INSERT INTO `db_springboot_backend`.`clientes` (`region_id`, `nombre`, `apellido`, `email`, `create_at`) VALUES (1, 'Ana', 'Lopez', 'ana.lopez@empresa.com', '2020-01-04');
INSERT INTO `db_springboot_backend`.`clientes` (`region_id`, `nombre`, `apellido`, `email`, `create_at`) VALUES (1, 'Javier', 'Cruz', 'javier.cruz@empresa.com', '2020-01-04');
INSERT INTO `db_springboot_backend`.`clientes` (`region_id`, `nombre`, `apellido`, `email`, `create_at`) VALUES (1, 'Manuel', 'Gonzales', 'manuel.gonzales@empresa.com', '2020-01-04');
INSERT INTO `db_springboot_backend`.`clientes` (`region_id`, `nombre`, `apellido`, `email`, `create_at`) VALUES (1, 'Luis', 'Palma', 'luis.palma@empresa.com', '2020-01-04');
INSERT INTO `db_springboot_backend`.`clientes` (`region_id`, `nombre`, `apellido`, `email`, `create_at`) VALUES (1, 'Edgard', 'Marquez', 'prueba1@empresa.com', '2020-01-01');
INSERT INTO `db_springboot_backend`.`clientes` (`region_id`, `nombre`, `apellido`, `email`, `create_at`) VALUES (1, 'Leon', 'Mendoza', 'prueba2@empresa.com', '2020-01-02');
INSERT INTO `db_springboot_backend`.`clientes` (`region_id`, `nombre`, `apellido`, `email`, `create_at`) VALUES (1, 'Martin', 'Lavalle', 'prueba3@empresa.com', '2020-01-03');
INSERT INTO `db_springboot_backend`.`clientes` (`region_id`, `nombre`, `apellido`, `email`, `create_at`) VALUES (1, 'Gonzalo', 'Garcia', 'prueba4@empresa.com', '2020-01-04');
INSERT INTO `db_springboot_backend`.`clientes` (`region_id`, `nombre`, `apellido`, `email`, `create_at`) VALUES (1, 'Maria', 'Perez', 'maria.perez@empresa.com', '2020-01-04');
INSERT INTO `db_springboot_backend`.`clientes` (`region_id`, `nombre`, `apellido`, `email`, `create_at`) VALUES (1, 'Ana', 'Lopez', 'ana.lopez@empresa.com', '2020-01-04');
INSERT INTO `db_springboot_backend`.`clientes` (`region_id`, `nombre`, `apellido`, `email`, `create_at`) VALUES (1, 'Javier', 'Cruz', 'javier.cruz@empresa.com', '2020-01-04');
INSERT INTO `db_springboot_backend`.`clientes` (`region_id`, `nombre`, `apellido`, `email`, `create_at`) VALUES (1, 'Manuel', 'Gonzales', 'manuel.gonzales@empresa.com', '2020-01-04');
INSERT INTO `db_springboot_backend`.`clientes` (`region_id`, `nombre`, `apellido`, `email`, `create_at`) VALUES (1, 'Luis', 'Palma', 'luis.palma@empresa.com', '2020-01-04');
INSERT INTO `db_springboot_backend`.`clientes` (`region_id`, `nombre`, `apellido`, `email`, `create_at`) VALUES (1, 'Edgard', 'Marquez', 'prueba1@empresa.com', '2020-01-01');
INSERT INTO `db_springboot_backend`.`clientes` (`region_id`, `nombre`, `apellido`, `email`, `create_at`) VALUES (1, 'Leon', 'Mendoza', 'prueba2@empresa.com', '2020-01-02');
INSERT INTO `db_springboot_backend`.`clientes` (`region_id`, `nombre`, `apellido`, `email`, `create_at`) VALUES (1, 'Martin', 'Lavalle', 'prueba3@empresa.com', '2020-01-03');
INSERT INTO `db_springboot_backend`.`clientes` (`region_id`, `nombre`, `apellido`, `email`, `create_at`) VALUES (1, 'Gonzalo', 'Garcia', 'prueba4@empresa.com', '2020-01-04');
INSERT INTO `db_springboot_backend`.`clientes` (`region_id`, `nombre`, `apellido`, `email`, `create_at`) VALUES (1, 'Maria', 'Perez', 'maria.perez@empresa.com', '2020-01-04');
INSERT INTO `db_springboot_backend`.`clientes` (`region_id`, `nombre`, `apellido`, `email`, `create_at`) VALUES (1, 'Ana', 'Lopez', 'ana.lopez@empresa.com', '2020-01-04');
INSERT INTO `db_springboot_backend`.`clientes` (`region_id`, `nombre`, `apellido`, `email`, `create_at`) VALUES (1, 'Javier', 'Cruz', 'javier.cruz@empresa.com', '2020-01-04');
INSERT INTO `db_springboot_backend`.`clientes` (`region_id`, `nombre`, `apellido`, `email`, `create_at`) VALUES (1, 'Manuel', 'Gonzales', 'manuel.gonzales@empresa.com', '2020-01-04');
INSERT INTO `db_springboot_backend`.`clientes` (`region_id`, `nombre`, `apellido`, `email`, `create_at`) VALUES (1, 'Luis', 'Palma', 'luis.palma@empresa.com', '2020-01-04');
INSERT INTO `db_springboot_backend`.`clientes` (`region_id`, `nombre`, `apellido`, `email`, `create_at`) VALUES (1, 'Edgard', 'Marquez', 'prueba1@empresa.com', '2020-01-01');
INSERT INTO `db_springboot_backend`.`clientes` (`region_id`, `nombre`, `apellido`, `email`, `create_at`) VALUES (1, 'Leon', 'Mendoza', 'prueba2@empresa.com', '2020-01-02');
INSERT INTO `db_springboot_backend`.`clientes` (`region_id`, `nombre`, `apellido`, `email`, `create_at`) VALUES (1, 'Martin', 'Lavalle', 'prueba3@empresa.com', '2020-01-03');
INSERT INTO `db_springboot_backend`.`clientes` (`region_id`, `nombre`, `apellido`, `email`, `create_at`) VALUES (1, 'Gonzalo', 'Garcia', 'prueba4@empresa.com', '2020-01-04');
INSERT INTO `db_springboot_backend`.`clientes` (`region_id`, `nombre`, `apellido`, `email`, `create_at`) VALUES (1, 'Maria', 'Perez', 'maria.perez@empresa.com', '2020-01-04');
INSERT INTO `db_springboot_backend`.`clientes` (`region_id`, `nombre`, `apellido`, `email`, `create_at`) VALUES (1, 'Ana', 'Lopez', 'ana.lopez@empresa.com', '2020-01-04');
INSERT INTO `db_springboot_backend`.`clientes` (`region_id`, `nombre`, `apellido`, `email`, `create_at`) VALUES (1, 'Javier', 'Cruz', 'javier.cruz@empresa.com', '2020-01-04');
INSERT INTO `db_springboot_backend`.`clientes` (`region_id`, `nombre`, `apellido`, `email`, `create_at`) VALUES (1, 'Manuel', 'Gonzales', 'manuel.gonzales@empresa.com', '2020-01-04');
INSERT INTO `db_springboot_backend`.`clientes` (`region_id`, `nombre`, `apellido`, `email`, `create_at`) VALUES (1, 'Luis', 'Palma', 'luis.palma@empresa.com', '2020-01-04');
INSERT INTO `db_springboot_backend`.`clientes` (`region_id`, `nombre`, `apellido`, `email`, `create_at`) VALUES (1, 'Edgard', 'Marquez', 'prueba1@empresa.com', '2020-01-01');
INSERT INTO `db_springboot_backend`.`clientes` (`region_id`, `nombre`, `apellido`, `email`, `create_at`) VALUES (1, 'Leon', 'Mendoza', 'prueba2@empresa.com', '2020-01-02');
INSERT INTO `db_springboot_backend`.`clientes` (`region_id`, `nombre`, `apellido`, `email`, `create_at`) VALUES (1, 'Martin', 'Lavalle', 'prueba3@empresa.com', '2020-01-03');
INSERT INTO `db_springboot_backend`.`clientes` (`region_id`, `nombre`, `apellido`, `email`, `create_at`) VALUES (1, 'Gonzalo', 'Garcia', 'prueba4@empresa.com', '2020-01-04');
INSERT INTO `db_springboot_backend`.`clientes` (`region_id`, `nombre`, `apellido`, `email`, `create_at`) VALUES (1, 'Maria', 'Perez', 'maria.perez@empresa.com', '2020-01-04');
INSERT INTO `db_springboot_backend`.`clientes` (`region_id`, `nombre`, `apellido`, `email`, `create_at`) VALUES (1, 'Ana', 'Lopez', 'ana.lopez@empresa.com', '2020-01-04');
INSERT INTO `db_springboot_backend`.`clientes` (`region_id`, `nombre`, `apellido`, `email`, `create_at`) VALUES (1, 'Javier', 'Cruz', 'javier.cruz@empresa.com', '2020-01-04');
INSERT INTO `db_springboot_backend`.`clientes` (`region_id`, `nombre`, `apellido`, `email`, `create_at`) VALUES (1, 'Manuel', 'Gonzales', 'manuel.gonzales@empresa.com', '2020-01-04');
INSERT INTO `db_springboot_backend`.`clientes` (`region_id`, `nombre`, `apellido`, `email`, `create_at`) VALUES (1, 'Luis', 'Palma', 'luis.palma@empresa.com', '2020-01-04');
INSERT INTO `db_springboot_backend`.`clientes` (`region_id`, `nombre`, `apellido`, `email`, `create_at`) VALUES (1, 'Edgard', 'Marquez', 'prueba1@empresa.com', '2020-01-01');
INSERT INTO `db_springboot_backend`.`clientes` (`region_id`, `nombre`, `apellido`, `email`, `create_at`) VALUES (1, 'Leon', 'Mendoza', 'prueba2@empresa.com', '2020-01-02');
INSERT INTO `db_springboot_backend`.`clientes` (`region_id`, `nombre`, `apellido`, `email`, `create_at`) VALUES (1, 'Martin', 'Lavalle', 'prueba3@empresa.com', '2020-01-03');
INSERT INTO `db_springboot_backend`.`clientes` (`region_id`, `nombre`, `apellido`, `email`, `create_at`) VALUES (1, 'Gonzalo', 'Garcia', 'prueba4@empresa.com', '2020-01-04');
INSERT INTO `db_springboot_backend`.`clientes` (`region_id`, `nombre`, `apellido`, `email`, `create_at`) VALUES (1, 'Maria', 'Perez', 'maria.perez@empresa.com', '2020-01-04');
INSERT INTO `db_springboot_backend`.`clientes` (`region_id`, `nombre`, `apellido`, `email`, `create_at`) VALUES (1, 'Ana', 'Lopez', 'ana.lopez@empresa.com', '2020-01-04');
INSERT INTO `db_springboot_backend`.`clientes` (`region_id`, `nombre`, `apellido`, `email`, `create_at`) VALUES (1, 'Javier', 'Cruz', 'javier.cruz@empresa.com', '2020-01-04');
INSERT INTO `db_springboot_backend`.`clientes` (`region_id`, `nombre`, `apellido`, `email`, `create_at`) VALUES (1, 'Manuel', 'Gonzales', 'manuel.gonzales@empresa.com', '2020-01-04');
INSERT INTO `db_springboot_backend`.`clientes` (`region_id`, `nombre`, `apellido`, `email`, `create_at`) VALUES (1, 'Luis', 'Palma', 'luis.palma@empresa.com', '2020-01-04');
INSERT INTO `db_springboot_backend`.`clientes` (`region_id`, `nombre`, `apellido`, `email`, `create_at`) VALUES (1, 'Edgard', 'Marquez', 'prueba1@empresa.com', '2020-01-01');
INSERT INTO `db_springboot_backend`.`clientes` (`region_id`, `nombre`, `apellido`, `email`, `create_at`) VALUES (1, 'Leon', 'Mendoza', 'prueba2@empresa.com', '2020-01-02');
INSERT INTO `db_springboot_backend`.`clientes` (`region_id`, `nombre`, `apellido`, `email`, `create_at`) VALUES (1, 'Martin', 'Lavalle', 'prueba3@empresa.com', '2020-01-03');
INSERT INTO `db_springboot_backend`.`clientes` (`region_id`, `nombre`, `apellido`, `email`, `create_at`) VALUES (1, 'Gonzalo', 'Garcia', 'prueba4@empresa.com', '2020-01-04');
INSERT INTO `db_springboot_backend`.`clientes` (`region_id`, `nombre`, `apellido`, `email`, `create_at`) VALUES (1, 'Maria', 'Perez', 'maria.perez@empresa.com', '2020-01-04');
INSERT INTO `db_springboot_backend`.`clientes` (`region_id`, `nombre`, `apellido`, `email`, `create_at`) VALUES (1, 'Ana', 'Lopez', 'ana.lopez@empresa.com', '2020-01-04');
INSERT INTO `db_springboot_backend`.`clientes` (`region_id`, `nombre`, `apellido`, `email`, `create_at`) VALUES (1, 'Javier', 'Cruz', 'javier.cruz@empresa.com', '2020-01-04');
INSERT INTO `db_springboot_backend`.`clientes` (`region_id`, `nombre`, `apellido`, `email`, `create_at`) VALUES (1, 'Manuel', 'Gonzales', 'manuel.gonzales@empresa.com', '2020-01-04');
INSERT INTO `db_springboot_backend`.`clientes` (`region_id`, `nombre`, `apellido`, `email`, `create_at`) VALUES (1, 'Luis', 'Palma', 'luis.palma@empresa.com', '2020-01-04');
INSERT INTO `db_springboot_backend`.`clientes` (`region_id`, `nombre`, `apellido`, `email`, `create_at`) VALUES (1, 'Edgard', 'Marquez', 'prueba1@empresa.com', '2020-01-01');
INSERT INTO `db_springboot_backend`.`clientes` (`region_id`, `nombre`, `apellido`, `email`, `create_at`) VALUES (1, 'Leon', 'Mendoza', 'prueba2@empresa.com', '2020-01-02');
INSERT INTO `db_springboot_backend`.`clientes` (`region_id`, `nombre`, `apellido`, `email`, `create_at`) VALUES (1, 'Martin', 'Lavalle', 'prueba3@empresa.com', '2020-01-03');
INSERT INTO `db_springboot_backend`.`clientes` (`region_id`, `nombre`, `apellido`, `email`, `create_at`) VALUES (1, 'Gonzalo', 'Garcia', 'prueba4@empresa.com', '2020-01-04');
INSERT INTO `db_springboot_backend`.`clientes` (`region_id`, `nombre`, `apellido`, `email`, `create_at`) VALUES (1, 'Maria', 'Perez', 'maria.perez@empresa.com', '2020-01-04');
INSERT INTO `db_springboot_backend`.`clientes` (`region_id`, `nombre`, `apellido`, `email`, `create_at`) VALUES (1, 'Ana', 'Lopez', 'ana.lopez@empresa.com', '2020-01-04');
INSERT INTO `db_springboot_backend`.`clientes` (`region_id`, `nombre`, `apellido`, `email`, `create_at`) VALUES (1, 'Javier', 'Cruz', 'javier.cruz@empresa.com', '2020-01-04');
INSERT INTO `db_springboot_backend`.`clientes` (`region_id`, `nombre`, `apellido`, `email`, `create_at`) VALUES (1, 'Manuel', 'Gonzales', 'manuel.gonzales@empresa.com', '2020-01-04');
INSERT INTO `db_springboot_backend`.`clientes` (`region_id`, `nombre`, `apellido`, `email`, `create_at`) VALUES (1, 'Luis', 'Palma', 'luis.palma@empresa.com', '2020-01-04');
INSERT INTO `db_springboot_backend`.`clientes` (`region_id`, `nombre`, `apellido`, `email`, `create_at`) VALUES (1, 'Edgard', 'Marquez', 'prueba1@empresa.com', '2020-01-01');
INSERT INTO `db_springboot_backend`.`clientes` (`region_id`, `nombre`, `apellido`, `email`, `create_at`) VALUES (1, 'Leon', 'Mendoza', 'prueba2@empresa.com', '2020-01-02');
INSERT INTO `db_springboot_backend`.`clientes` (`region_id`, `nombre`, `apellido`, `email`, `create_at`) VALUES (1, 'Martin', 'Lavalle', 'prueba3@empresa.com', '2020-01-03');
INSERT INTO `db_springboot_backend`.`clientes` (`region_id`, `nombre`, `apellido`, `email`, `create_at`) VALUES (1, 'Gonzalo', 'Garcia', 'prueba4@empresa.com', '2020-01-04');
INSERT INTO `db_springboot_backend`.`clientes` (`region_id`, `nombre`, `apellido`, `email`, `create_at`) VALUES (1, 'Maria', 'Perez', 'maria.perez@empresa.com', '2020-01-04');
INSERT INTO `db_springboot_backend`.`clientes` (`region_id`, `nombre`, `apellido`, `email`, `create_at`) VALUES (1, 'Ana', 'Lopez', 'ana.lopez@empresa.com', '2020-01-04');
INSERT INTO `db_springboot_backend`.`clientes` (`region_id`, `nombre`, `apellido`, `email`, `create_at`) VALUES (1, 'Javier', 'Cruz', 'javier.cruz@empresa.com', '2020-01-04');
INSERT INTO `db_springboot_backend`.`clientes` (`region_id`, `nombre`, `apellido`, `email`, `create_at`) VALUES (1, 'Manuel', 'Gonzales', 'manuel.gonzales@empresa.com', '2020-01-04');
INSERT INTO `db_springboot_backend`.`clientes` (`region_id`, `nombre`, `apellido`, `email`, `create_at`) VALUES (1, 'Luis', 'Palma', 'luis.palma@empresa.com', '2020-01-04');
INSERT INTO `db_springboot_backend`.`clientes` (`region_id`, `nombre`, `apellido`, `email`, `create_at`) VALUES (1, 'Edgard', 'Marquez', 'prueba1@empresa.com', '2020-01-01');
INSERT INTO `db_springboot_backend`.`clientes` (`region_id`, `nombre`, `apellido`, `email`, `create_at`) VALUES (1, 'Leon', 'Mendoza', 'prueba2@empresa.com', '2020-01-02');
INSERT INTO `db_springboot_backend`.`clientes` (`region_id`, `nombre`, `apellido`, `email`, `create_at`) VALUES (1, 'Martin', 'Lavalle', 'prueba3@empresa.com', '2020-01-03');
INSERT INTO `db_springboot_backend`.`clientes` (`region_id`, `nombre`, `apellido`, `email`, `create_at`) VALUES (1, 'Gonzalo', 'Garcia', 'prueba4@empresa.com', '2020-01-04');
INSERT INTO `db_springboot_backend`.`clientes` (`region_id`, `nombre`, `apellido`, `email`, `create_at`) VALUES (1, 'Maria', 'Perez', 'maria.perez@empresa.com', '2020-01-04');
INSERT INTO `db_springboot_backend`.`clientes` (`region_id`, `nombre`, `apellido`, `email`, `create_at`) VALUES (1, 'Ana', 'Lopez', 'ana.lopez@empresa.com', '2020-01-04');
INSERT INTO `db_springboot_backend`.`clientes` (`region_id`, `nombre`, `apellido`, `email`, `create_at`) VALUES (1, 'Javier', 'Cruz', 'javier.cruz@empresa.com', '2020-01-04');
INSERT INTO `db_springboot_backend`.`clientes` (`region_id`, `nombre`, `apellido`, `email`, `create_at`) VALUES (1, 'Manuel', 'Gonzales', 'manuel.gonzales@empresa.com', '2020-01-04');
INSERT INTO `db_springboot_backend`.`clientes` (`region_id`, `nombre`, `apellido`, `email`, `create_at`) VALUES (1, 'Luis', 'Palma', 'luis.palma@empresa.com', '2020-01-04');
INSERT INTO `db_springboot_backend`.`clientes` (`region_id`, `nombre`, `apellido`, `email`, `create_at`) VALUES (1, 'Edgard', 'Marquez', 'prueba1@empresa.com', '2020-01-01');
INSERT INTO `db_springboot_backend`.`clientes` (`region_id`, `nombre`, `apellido`, `email`, `create_at`) VALUES (1, 'Leon', 'Mendoza', 'prueba2@empresa.com', '2020-01-02');
INSERT INTO `db_springboot_backend`.`clientes` (`region_id`, `nombre`, `apellido`, `email`, `create_at`) VALUES (1, 'Martin', 'Lavalle', 'prueba3@empresa.com', '2020-01-03');
INSERT INTO `db_springboot_backend`.`clientes` (`region_id`, `nombre`, `apellido`, `email`, `create_at`) VALUES (1, 'Gonzalo', 'Garcia', 'prueba4@empresa.com', '2020-01-04');
INSERT INTO `db_springboot_backend`.`clientes` (`region_id`, `nombre`, `apellido`, `email`, `create_at`) VALUES (1, 'Maria', 'Perez', 'maria.perez@empresa.com', '2020-01-04');
INSERT INTO `db_springboot_backend`.`clientes` (`region_id`, `nombre`, `apellido`, `email`, `create_at`) VALUES (1, 'Ana', 'Lopez', 'ana.lopez@empresa.com', '2020-01-04');
INSERT INTO `db_springboot_backend`.`clientes` (`region_id`, `nombre`, `apellido`, `email`, `create_at`) VALUES (1, 'Javier', 'Cruz', 'javier.cruz@empresa.com', '2020-01-04');
INSERT INTO `db_springboot_backend`.`clientes` (`region_id`, `nombre`, `apellido`, `email`, `create_at`) VALUES (1, 'Manuel', 'Gonzales', 'manuel.gonzales@empresa.com', '2020-01-04');
INSERT INTO `db_springboot_backend`.`clientes` (`region_id`, `nombre`, `apellido`, `email`, `create_at`) VALUES (1, 'Luis', 'Palma', 'luis.palma@empresa.com', '2020-01-04');
INSERT INTO `db_springboot_backend`.`clientes` (`region_id`, `nombre`, `apellido`, `email`, `create_at`) VALUES (1, 'Edgard', 'Marquez', 'prueba1@empresa.com', '2020-01-01');
INSERT INTO `db_springboot_backend`.`clientes` (`region_id`, `nombre`, `apellido`, `email`, `create_at`) VALUES (1, 'Leon', 'Mendoza', 'prueba2@empresa.com', '2020-01-02');
INSERT INTO `db_springboot_backend`.`clientes` (`region_id`, `nombre`, `apellido`, `email`, `create_at`) VALUES (1, 'Martin', 'Lavalle', 'prueba3@empresa.com', '2020-01-03');
INSERT INTO `db_springboot_backend`.`clientes` (`region_id`, `nombre`, `apellido`, `email`, `create_at`) VALUES (1, 'Gonzalo', 'Garcia', 'prueba4@empresa.com', '2020-01-04');
INSERT INTO `db_springboot_backend`.`clientes` (`region_id`, `nombre`, `apellido`, `email`, `create_at`) VALUES (1, 'Maria', 'Perez', 'maria.perez@empresa.com', '2020-01-04');
INSERT INTO `db_springboot_backend`.`clientes` (`region_id`, `nombre`, `apellido`, `email`, `create_at`) VALUES (1, 'Ana', 'Lopez', 'ana.lopez@empresa.com', '2020-01-04');
INSERT INTO `db_springboot_backend`.`clientes` (`region_id`, `nombre`, `apellido`, `email`, `create_at`) VALUES (1, 'Javier', 'Cruz', 'javier.cruz@empresa.com', '2020-01-04');
INSERT INTO `db_springboot_backend`.`clientes` (`region_id`, `nombre`, `apellido`, `email`, `create_at`) VALUES (1, 'Manuel', 'Gonzales', 'manuel.gonzales@empresa.com', '2020-01-04');
INSERT INTO `db_springboot_backend`.`clientes` (`region_id`, `nombre`, `apellido`, `email`, `create_at`) VALUES (1, 'Luis', 'Palma', 'luis.palma@empresa.com', '2020-01-04');
INSERT INTO `db_springboot_backend`.`clientes` (`region_id`, `nombre`, `apellido`, `email`, `create_at`) VALUES (1, 'Edgard', 'Marquez', 'prueba1@empresa.com', '2020-01-01');
INSERT INTO `db_springboot_backend`.`clientes` (`region_id`, `nombre`, `apellido`, `email`, `create_at`) VALUES (1, 'Leon', 'Mendoza', 'prueba2@empresa.com', '2020-01-02');
INSERT INTO `db_springboot_backend`.`clientes` (`region_id`, `nombre`, `apellido`, `email`, `create_at`) VALUES (1, 'Martin', 'Lavalle', 'prueba3@empresa.com', '2020-01-03');
INSERT INTO `db_springboot_backend`.`clientes` (`region_id`, `nombre`, `apellido`, `email`, `create_at`) VALUES (1, 'Gonzalo', 'Garcia', 'prueba4@empresa.com', '2020-01-04');
INSERT INTO `db_springboot_backend`.`clientes` (`region_id`, `nombre`, `apellido`, `email`, `create_at`) VALUES (1, 'Maria', 'Perez', 'maria.perez@empresa.com', '2020-01-04');
INSERT INTO `db_springboot_backend`.`clientes` (`region_id`, `nombre`, `apellido`, `email`, `create_at`) VALUES (1, 'Ana', 'Lopez', 'ana.lopez@empresa.com', '2020-01-04');
INSERT INTO `db_springboot_backend`.`clientes` (`region_id`, `nombre`, `apellido`, `email`, `create_at`) VALUES (1, 'Javier', 'Cruz', 'javier.cruz@empresa.com', '2020-01-04');
INSERT INTO `db_springboot_backend`.`clientes` (`region_id`, `nombre`, `apellido`, `email`, `create_at`) VALUES (1, 'Manuel', 'Gonzales', 'manuel.gonzales@empresa.com', '2020-01-04');
INSERT INTO `db_springboot_backend`.`clientes` (`region_id`, `nombre`, `apellido`, `email`, `create_at`) VALUES (1, 'Luis', 'Palma', 'luis.palma@empresa.com', '2020-01-04');
INSERT INTO `db_springboot_backend`.`clientes` (`region_id`, `nombre`, `apellido`, `email`, `create_at`) VALUES (1, 'Edgard', 'Marquez', 'prueba1@empresa.com', '2020-01-01');
INSERT INTO `db_springboot_backend`.`clientes` (`region_id`, `nombre`, `apellido`, `email`, `create_at`) VALUES (1, 'Leon', 'Mendoza', 'prueba2@empresa.com', '2020-01-02');
INSERT INTO `db_springboot_backend`.`clientes` (`region_id`, `nombre`, `apellido`, `email`, `create_at`) VALUES (1, 'Martin', 'Lavalle', 'prueba3@empresa.com', '2020-01-03');
INSERT INTO `db_springboot_backend`.`clientes` (`region_id`, `nombre`, `apellido`, `email`, `create_at`) VALUES (1, 'Gonzalo', 'Garcia', 'prueba4@empresa.com', '2020-01-04');
INSERT INTO `db_springboot_backend`.`clientes` (`region_id`, `nombre`, `apellido`, `email`, `create_at`) VALUES (1, 'Maria', 'Perez', 'maria.perez@empresa.com', '2020-01-04');
INSERT INTO `db_springboot_backend`.`clientes` (`region_id`, `nombre`, `apellido`, `email`, `create_at`) VALUES (1, 'Ana', 'Lopez', 'ana.lopez@empresa.com', '2020-01-04');
INSERT INTO `db_springboot_backend`.`clientes` (`region_id`, `nombre`, `apellido`, `email`, `create_at`) VALUES (1, 'Javier', 'Cruz', 'javier.cruz@empresa.com', '2020-01-04');
INSERT INTO `db_springboot_backend`.`clientes` (`region_id`, `nombre`, `apellido`, `email`, `create_at`) VALUES (1, 'Manuel', 'Gonzales', 'manuel.gonzales@empresa.com', '2020-01-04');
INSERT INTO `db_springboot_backend`.`clientes` (`region_id`, `nombre`, `apellido`, `email`, `create_at`) VALUES (1, 'Luis', 'Palma', 'luis.palma@empresa.com', '2020-01-04');

INSERT INTO `db_springboot_backend`.`usuarios` (`username`, `password`, `enabled`, `nombre`, `apellido`, `email`) VALUES ('edgard', '$2a$10$2w1Fz4FZV9pG2fBlNaXa3.2JXEhstv5UcJNAbsqyyRt8CT.b.EnUG', 1, 'Edgard', 'Marquez', 'edgard.marquez@gmail.com');
INSERT INTO `db_springboot_backend`.`usuarios` (`username`, `password`, `enabled`, `nombre`, `apellido`, `email`) VALUES ('admin', '$2a$10$VQ2MDdihtWV8EoFihmxJUeAyaSjKYkdes0BtNtSszF1b8dSkCjHDG', 1, 'John', 'Doe', 'john.doe@gmail.com');

INSERT INTO `db_springboot_backend`.`roles` (`nombre`) VALUES ('ROLE_USER');
INSERT INTO `db_springboot_backend`.`roles` (`nombre`) VALUES ('ROLE_ADMIN');

INSERT INTO `db_springboot_backend`.`usuarios_roles` (`usuario_id`, `rol_id`) VALUES (1, 1);
INSERT INTO `db_springboot_backend`.`usuarios_roles` (`usuario_id`, `rol_id`) VALUES (2, 1);
INSERT INTO `db_springboot_backend`.`usuarios_roles` (`usuario_id`, `rol_id`) VALUES (2, 2);

INSERT INTO `db_springboot_backend`.`productos` (`nombre`, `precio`, `create_at`) VALUES ('Sony Camara Alfa', 12345, NOW());
INSERT INTO `db_springboot_backend`.`productos` (`nombre`, `precio`, `create_at`) VALUES ('Sony Laptop S10', 54321, NOW());
INSERT INTO `db_springboot_backend`.`productos` (`nombre`, `precio`, `create_at`) VALUES ('Panasonic TV 45 Smart', 98765, NOW());
INSERT INTO `db_springboot_backend`.`productos` (`nombre`, `precio`, `create_at`) VALUES ('Panasonic Equipo Sound', 56789, NOW());
INSERT INTO `db_springboot_backend`.`productos` (`nombre`, `precio`, `create_at`) VALUES ('Samsung Refrigeradora 25', 10000, NOW());
INSERT INTO `db_springboot_backend`.`productos` (`nombre`, `precio`, `create_at`) VALUES ('Samsing Celular S3', 20000, NOW());
INSERT INTO `db_springboot_backend`.`productos` (`nombre`, `precio`, `create_at`) VALUES ('LG TV 32 Smart', 30000, NOW());

INSERT INTO `db_springboot_backend`.`facturas` (`descripcion`, `observacion`, `cliente_id`, `create_at`) VALUES ('FACTURA 1', null, 1, NOW());
INSERT INTO `db_springboot_backend`.`facturas_items` (`cantidad`, `factura_id`, `producto_id`) VALUES (1, 1, 1);
INSERT INTO `db_springboot_backend`.`facturas_items` (`cantidad`, `factura_id`, `producto_id`) VALUES (2, 1, 4);
INSERT INTO `db_springboot_backend`.`facturas_items` (`cantidad`, `factura_id`, `producto_id`) VALUES (1, 1, 5);
INSERT INTO `db_springboot_backend`.`facturas_items` (`cantidad`, `factura_id`, `producto_id`) VALUES (1, 1, 7);

INSERT INTO `db_springboot_backend`.`facturas` (`descripcion`, `observacion`, `cliente_id`, `create_at`) VALUES ('FACTURA 2', 'OBSERVACIONES', 1, NOW());
INSERT INTO `db_springboot_backend`.`facturas_items` (`cantidad`, `factura_id`, `producto_id`) VALUES (3, 2, 6);
